#!/usr/bin/env python3
"""Deploy the stack with Docker Compose and run integration checks.

Used by the ADR integration-tester agent and local pre-PR validation.

From repository root:

    python scripts/run_compose_integration.py
    python scripts/run_compose_integration.py --keep
    python scripts/run_compose_integration.py --skip-deploy   # stack already up

Exits 0 when required checks pass, 1 on failure, 2 when Docker unavailable (skip).

Before first run with bundled Ollama, pull the embed model:

    docker exec codeindexer_ollama ollama pull unclemusclez/jina-embeddings-v2-base-code
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MCP_SERVER = REPO_ROOT / "mcp_server"
ENV_FILE = REPO_ROOT / ".env.compose.integration"
COMPOSE_BASE = ["docker", "compose", "--env-file", str(ENV_FILE)]
COMPOSE_FILES = [
    "-f",
    str(REPO_ROOT / "docker-compose.yml"),
    "-f",
    str(REPO_ROOT / "docker-compose.ollama.yml"),
]
COMPOSE_PROFILE = "bundled-ollama"
SERVICES = ("qdrant", "ollama", "mcp_server")
QDRANT_URL = "http://127.0.0.1:6333"
MCP_HEALTH_URL = "http://127.0.0.1:8000/health"
OLLAMA_URL = "http://127.0.0.1:11434"

# Host-side pytest/smoke must match compose Jina preset — not developer .env.
_INTEGRATION_EMBED_ENV = {
    "DENSE_EMBED_MODEL": "jinaai/jina-embeddings-v2-base-code",
    "OLLAMA_EMBED_MODEL": "unclemusclez/jina-embeddings-v2-base-code",
    "DENSE_EMBED_VECTOR_SIZE": "768",
    "OLLAMA_URL": OLLAMA_URL,
    "SPARSE_EMBED_MODEL": "Qdrant/bm25",
    "SPARSE_THREADS": "2",
}


def _host_test_env() -> dict[str, str]:
    env = os.environ.copy()
    env["QDRANT_URL"] = QDRANT_URL
    env.update(_INTEGRATION_EMBED_ENV)
    return env


def _run(cmd: list[str], *, cwd: Path | None = None, env: dict | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        cwd=cwd or REPO_ROOT,
        env=env,
        text=True,
        capture_output=True,
    )


def docker_available() -> bool:
    return _run(["docker", "info"]).returncode == 0


def write_integration_env(workspace_root: Path) -> None:
    """Minimal compose env for integration — does not touch developer .env."""
    workspace = workspace_root.resolve()
    content = f"""# Generated by scripts/run_compose_integration.py — safe to delete
# Pre-step (bundled Ollama): docker exec codeindexer_ollama ollama pull unclemusclez/jina-embeddings-v2-base-code
WORKSPACE_ROOT={workspace}
MCP_MEM_LIMIT=4g
QDRANT_MEM_LIMIT=2g
MCP_CPUS=4
QDRANT_CPUS=2
OMP_NUM_THREADS=2
DENSE_EMBED_MODEL=jinaai/jina-embeddings-v2-base-code
SPARSE_EMBED_MODEL=Qdrant/bm25
DENSE_EMBED_VECTOR_SIZE=768
SPARSE_THREADS=2
COMPOSE_PROFILES={COMPOSE_PROFILE}
OLLAMA_URL=http://ollama:11434
OLLAMA_EMBED_MODEL=unclemusclez/jina-embeddings-v2-base-code
OLLAMA_MEM_LIMIT=3g
OLLAMA_CPUS=2
RERANK_ENABLED=false
"""
    ENV_FILE.write_text(content, encoding="utf-8")


def compose_cmd(*args: str) -> list[str]:
    return [*COMPOSE_BASE, *COMPOSE_FILES, *args]


def deploy() -> tuple[bool, str]:
    build = _run(compose_cmd("build", "mcp_server"))
    if build.returncode != 0:
        return False, build.stderr or build.stdout or "compose build failed"
    up = _run(
        compose_cmd(
            "--profile",
            COMPOSE_PROFILE,
            "up",
            "-d",
            "--wait",
            *SERVICES,
        )
    )
    if up.returncode != 0:
        return False, up.stderr or up.stdout or "compose up failed"
    return True, "deployed"


def http_ok(url: str, timeout: float = 3.0) -> tuple[bool, str]:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            body = resp.read(500).decode("utf-8", errors="replace")
            return True, body[:200]
    except urllib.error.HTTPError as exc:
        return False, f"HTTP {exc.code}"
    except Exception as exc:
        return False, str(exc)


def wait_http(url: str, *, attempts: int = 30, interval: float = 2.0) -> tuple[bool, str]:
    last = ""
    for _ in range(attempts):
        ok, msg = http_ok(url)
        if ok:
            return True, msg
        last = msg
        time.sleep(interval)
    return False, last


def run_pytest_integration() -> tuple[bool, str]:
    proc = _run(
        ["uv", "run", "pytest", "tests/test_storage_integration.py", "-q", "--tb=short"],
        cwd=MCP_SERVER,
        env=_host_test_env(),
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode == 0, out.strip()[-2000:]


def run_smoke_optional() -> tuple[str, str]:
    """recommend_code smoke — optional when Ollama + indexed collection available."""
    proc = _run(
        ["uv", "run", "python", "scripts/smoke_recommend_code.py"],
        cwd=MCP_SERVER,
        env=_host_test_env(),
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode == 0 and "SKIP:" in out:
        return "skipped", out.strip()[-500:]
    if proc.returncode == 0:
        return "pass", out.strip()[-500:]
    return "fail", out.strip()[-1000:]


def teardown() -> None:
    _run(compose_cmd("--profile", COMPOSE_PROFILE, "down", "--remove-orphans"))


def main() -> int:
    parser = argparse.ArgumentParser(description="Docker Compose integration harness")
    parser.add_argument("--keep", action="store_true", help="Leave stack running after tests")
    parser.add_argument("--skip-deploy", action="store_true", help="Assume stack already up")
    parser.add_argument("--json", action="store_true", help="Print machine-readable report on stdout")
    args = parser.parse_args()

    report: dict = {
        "deploy": {"status": "pending", "detail": ""},
        "qdrant_health": {"status": "pending", "detail": ""},
        "mcp_health": {"status": "pending", "detail": ""},
        "ollama_health": {"status": "pending", "detail": ""},
        "pytest_integration": {"status": "pending", "detail": ""},
        "smoke_recommend": {"status": "pending", "detail": ""},
        "verdict": "pending",
    }

    if not docker_available():
        report["verdict"] = "skip"
        report["deploy"] = {"status": "skip", "detail": "docker not available"}
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print("SKIP: Docker not available")
        return 2

    write_integration_env(REPO_ROOT)

    try:
        if args.skip_deploy:
            report["deploy"] = {"status": "skipped", "detail": "--skip-deploy"}
        else:
            ok, detail = deploy()
            report["deploy"] = {"status": "pass" if ok else "fail", "detail": detail}
            if not ok:
                report["verdict"] = "fail"
                if args.json:
                    print(json.dumps(report, indent=2))
                return 1

        ok, detail = wait_http(f"{QDRANT_URL}/healthz")
        report["qdrant_health"] = {"status": "pass" if ok else "fail", "detail": detail}

        ok, detail = wait_http(MCP_HEALTH_URL)
        report["mcp_health"] = {"status": "pass" if ok else "fail", "detail": detail}

        ok, detail = http_ok(f"{OLLAMA_URL}/api/tags")
        report["ollama_health"] = {
            "status": "pass" if ok else "warn",
            "detail": detail if ok else detail,
        }

        ok, detail = run_pytest_integration()
        report["pytest_integration"] = {"status": "pass" if ok else "fail", "detail": detail}

        smoke_status, smoke_detail = run_smoke_optional()
        report["smoke_recommend"] = {"status": smoke_status, "detail": smoke_detail}

        required_ok = all(
            report[k]["status"] in ("pass", "skipped")
            for k in ("deploy", "qdrant_health", "mcp_health", "pytest_integration")
        )
        report["verdict"] = "pass" if required_ok else "fail"

        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print(f"Verdict: {report['verdict']}")
            for name, row in report.items():
                if name == "verdict":
                    continue
                print(f"  {name}: {row['status']}")

        return 0 if required_ok else 1
    finally:
        if not args.keep and not args.skip_deploy:
            teardown()


if __name__ == "__main__":
    raise SystemExit(main())
