#!/usr/bin/env python3
"""Deploy the Aspire/.NET stack with Docker Compose and run integration checks.

Used by the ADR integration-tester agent and local pre-PR validation.

From repository root::

    python scripts/run_compose_integration.py
    python scripts/run_compose_integration.py --keep
    python scripts/run_compose_integration.py --skip-deploy
    python scripts/run_compose_integration.py --json --quality-validation
    ACCELERATOR=cpu python scripts/run_compose_integration.py --json --external-tei

Production default is Aspire (ADR 0030 Phase 7). ``--aspire-stack`` is a no-op alias.

Exits 0 when required checks pass, 1 on failure, 2 when Docker unavailable (skip).
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
from collections.abc import Callable
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.accelerator import (  # noqa: E402
    GpuRequiredError,
    container_arch,
    get_accelerator,
    require_gpu,
    tei_image_default,
)
from scripts.aspire_compose import aspire_compose_file_args  # noqa: E402

BENCHMARKS = REPO_ROOT / "benchmarks"
ENV_FILE = REPO_ROOT / ".env.compose.integration"
EVAL_BASELINE = BENCHMARKS / "benchmarks" / "fixtures" / "eval_baseline.json"
BENCH_BASELINE = BENCHMARKS / "benchmarks" / "baseline.json"
REINDEX_SCRIPT = REPO_ROOT / "scripts" / "reindex_graphrag.py"
ASPIRE_FASTEMBED_CACHE = REPO_ROOT / ".aspire-fastembed-cache"
ASPIRE_SERVICES = ("qdrant", "tei", "colbert", "mcp")
ASPIRE_SERVICES_EXTERNAL_TEI = ("qdrant", "colbert", "mcp")
ASPIRE_MCP_CONTAINER = "codeindexer_mcp_dotnet"
COLBERT_HEALTH_URL = "http://127.0.0.1:8082/health"
COLBERT_EMBED_MODEL = "colbert-ir/colbertv2.0"
DOTNET_SDK_IMAGE = os.environ.get("DOTNET_SDK_IMAGE", "mcr.microsoft.com/dotnet/sdk:10.0")
QDRANT_URL = "http://127.0.0.1:6333"
MCP_HEALTH_URL = "http://127.0.0.1:8000/health"
MCP_ALIVE_URL = "http://127.0.0.1:8000/alive"
MCP_URL = "http://127.0.0.1:8000/mcp"
TEI_URL = "http://127.0.0.1:8080"
HOST_TEI_URL = "http://127.0.0.1:8080"
EXTERNAL_TEI_COMPOSE_URL = "http://host.docker.internal:8080"
TEI_CONTAINER = "codeindexer_tei"
NEO4J_URL = "http://127.0.0.1:7474"
NEO4J_CONTAINER = "codeindexer_neo4j"
GRAPH_INTEGRATION_PASSWORD = "graph-integration-pw"
JINA_DENSE_MODEL = "jinaai/jina-embeddings-v2-base-code"
DENSE_VECTOR_SIZE = 768

_INTEGRATION_EMBED_ENV = {
    "DENSE_EMBED_MODEL": JINA_DENSE_MODEL,
    "DENSE_EMBED_VECTOR_SIZE": str(DENSE_VECTOR_SIZE),
    "TEI_URL": TEI_URL,
    "SPARSE_EMBED_MODEL": "Qdrant/bm25",
    "SPARSE_THREADS": "2",
}


def _host_test_env() -> dict[str, str]:
    env = os.environ.copy()
    env["QDRANT_URL"] = QDRANT_URL
    env.update(_INTEGRATION_EMBED_ENV)
    return env


def _run(cmd: list[str], *, cwd: Path | None = None, env: dict | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        cwd=cwd or REPO_ROOT,
        env=env,
        text=True,
        capture_output=True,
    )


def docker_available() -> bool:
    return _run(["docker", "info"]).returncode == 0


def write_integration_env(
    workspace_root: Path,
    *,
    graph: bool = False,
    external_tei: bool = False,
    quality_rerank: bool = False,
) -> None:
    """Minimal compose env for integration — does not touch developer .env."""
    workspace = workspace_root.resolve()
    aspire_cache = ASPIRE_FASTEMBED_CACHE.resolve()
    accelerator = "cpu" if external_tei else get_accelerator()
    env_for_defaults = {"ACCELERATOR": accelerator}
    tei_image_line = ""
    mkl_line = ""
    if accelerator == "cpu" and not external_tei:
        tei_image = tei_image_default(env_for_defaults)
        tei_image_line = f"TEI_IMAGE={tei_image}\n"
        if container_arch() == "amd64" and "arm64" not in tei_image.lower():
            mkl_line = "TEI_MKL_INSTRUCTIONS=AVX2\n"

    tei_mem_limit = "8g" if accelerator == "cpu" else "4g"
    tei_cpus = "4" if accelerator == "cpu" else "2"
    tei_batch_tokens_line = (
        "TEI_MAX_BATCH_TOKENS=1024\nMAX_DENSE_EMBED_TOKENS=1024\n"
        if accelerator == "cpu"
        else ""
    )

    tei_url = EXTERNAL_TEI_COMPOSE_URL if external_tei else "http://tei:80"
    # .NET config uses Section__Property; also keep flat TEI_URL for scripts.
    tei_dotnet = (
        f"Tei__Url={tei_url}\n" if external_tei else f"Tei__Url={tei_url}\n"
    )

    content = f"""# Generated by scripts/run_compose_integration.py — safe to delete
WORKSPACE_ROOT={workspace}
WORKSPACE_PATH={workspace}
ASPIRE_FASTEMBED_CACHE={aspire_cache}
ACCELERATOR={accelerator}
{tei_image_line}MCP_MEM_LIMIT=4g
QDRANT_MEM_LIMIT=2g
MCP_CPUS=4
QDRANT_CPUS=2
OMP_NUM_THREADS=2
DENSE_EMBED_MODEL={JINA_DENSE_MODEL}
SPARSE_EMBED_MODEL=Qdrant/bm25
DENSE_EMBED_VECTOR_SIZE={DENSE_VECTOR_SIZE}
SPARSE_THREADS=2
TEI_URL={tei_url}
{tei_dotnet}TEI_TIMEOUT=600
QDRANT_TIMEOUT=120
TEI_EMBED_BATCH_SIZE=16
TEI_MEM_LIMIT={tei_mem_limit}
TEI_CPUS={tei_cpus}
{tei_batch_tokens_line}{mkl_line}FLUSH_EVERY=128
UPSERT_BATCH={"25" if quality_rerank else "64"}
INDEX_BATCH_SIZE=16
RERANK_ENABLED={"true" if quality_rerank else "false"}
Embedding__RerankEnabled={"true" if quality_rerank else "false"}
COLBERT_EMBED_BACKEND=remote
COLBERT_EMBED_MODEL={COLBERT_EMBED_MODEL}
COLBERT_TIMEOUT=300
"""
    if graph:
        content += (
            "GRAPH_ENABLED=true\n"
            "Graph__Enabled=true\n"
            f"NEO4J_PASSWORD={GRAPH_INTEGRATION_PASSWORD}\n"
            "NEO4J_USER=neo4j\n"
            "NEO4J_URI=bolt://neo4j:7687\n"
            "NEO4J_DATABASE=neo4j\n"
            "GRAPH_MAX_HOPS=2\n"
            "GRAPH_MAX_NODES=200\n"
        )
    ENV_FILE.write_text(content, encoding="utf-8")


def aspire_compose_cmd(
    *args: str,
    graph: bool = False,
    gpu_colbert: bool = False,
    external_tei: bool = False,
) -> list[str]:
    env = dict(os.environ)
    if ENV_FILE.is_file():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            env[key] = value
    file_args = aspire_compose_file_args(
        repo_root=REPO_ROOT,
        env=env,
        include_tei=not external_tei,
        include_neo4j=graph,
        gpu_colbert=gpu_colbert,
    )
    return ["docker", "compose", "--env-file", str(ENV_FILE), *file_args, *args]


def seed_aspire_sparse_cache() -> tuple[bool, str]:
    """Download Qdrant/bm25 into ASPIRE_FASTEMBED_CACHE for the .NET OnnxSparseEmbedder."""
    ASPIRE_FASTEMBED_CACHE.mkdir(parents=True, exist_ok=True)
    cache = str(ASPIRE_FASTEMBED_CACHE.resolve())
    os.environ["ASPIRE_FASTEMBED_CACHE"] = cache
    proc = _run(
        [
            "uv",
            "run",
            "python",
            "-c",
            (
                "from fastembed.sparse import SparseTextEmbedding; "
                f"SparseTextEmbedding(model_name='Qdrant/bm25', cache_dir=r'{cache}')"
            ),
        ],
        cwd=BENCHMARKS,
    )
    detail = ((proc.stdout or "") + (proc.stderr or "")).strip()[-1500:]
    if proc.returncode != 0:
        return False, detail or "sparse model seed failed"
    return True, f"seeded BM25 at {cache}"


def seed_aspire_colbert_cache() -> tuple[bool, str]:
    """Download ColBERT ONNX artifacts into ASPIRE_FASTEMBED_CACHE for ColbertWorker."""
    ASPIRE_FASTEMBED_CACHE.mkdir(parents=True, exist_ok=True)
    cache = str(ASPIRE_FASTEMBED_CACHE.resolve())
    proc = _run(
        [
            "uv",
            "run",
            "python",
            "-c",
            (
                "from fastembed.late_interaction import LateInteractionTextEmbedding; "
                f"LateInteractionTextEmbedding(model_name='{COLBERT_EMBED_MODEL}', "
                f"cache_dir=r'{cache}')"
            ),
        ],
        cwd=BENCHMARKS,
    )
    detail = ((proc.stdout or "") + (proc.stderr or "")).strip()[-1500:]
    if proc.returncode != 0:
        return False, detail or "colbert model seed failed"
    return True, f"seeded ColBERT at {cache}"


def _nvidia_available() -> bool:
    return _run(["nvidia-smi"]).returncode == 0


def deploy_aspire_stack(
    *,
    graph: bool = False,
    quality_rerank: bool = False,
    external_tei: bool = False,
) -> tuple[bool, str]:
    seeded, seed_detail = seed_aspire_sparse_cache()
    if not seeded:
        return False, f"aspire sparse cache seed failed — {seed_detail}"
    colbert_seeded, colbert_detail = seed_aspire_colbert_cache()
    if not colbert_seeded:
        return False, f"aspire ColBERT cache seed failed — {colbert_detail}"
    seed_detail = f"{seed_detail}; {colbert_detail}"

    accelerator = get_accelerator()
    gpu_colbert = accelerator == "gpu" and not external_tei
    if gpu_colbert and not _nvidia_available():
        return False, "ACCELERATOR=gpu but nvidia-smi failed (no NVIDIA GPU / driver)"

    if graph:
        _run(
            aspire_compose_cmd(
                "down",
                "--remove-orphans",
                "-v",
                graph=True,
                gpu_colbert=gpu_colbert,
                external_tei=external_tei,
            )
        )
    build = _run(
        aspire_compose_cmd(
            "build",
            "mcp",
            "colbert",
            graph=graph,
            gpu_colbert=gpu_colbert,
            external_tei=external_tei,
        )
    )
    if build.returncode != 0:
        return False, build.stderr or build.stdout or "aspire compose build failed"
    services = (
        ASPIRE_SERVICES_EXTERNAL_TEI if external_tei else ASPIRE_SERVICES
    ) + (("neo4j",) if graph else ())
    up = _run(
        aspire_compose_cmd(
            "up",
            "-d",
            "--wait",
            *services,
            graph=graph,
            gpu_colbert=gpu_colbert,
            external_tei=external_tei,
        )
    )
    if up.returncode != 0:
        return False, up.stderr or up.stdout or "aspire compose up failed"
    detail = f"aspire stack deployed ({seed_detail})"
    if graph:
        detail += " with neo4j graph overlay"
    if gpu_colbert:
        detail += " with GPU ColBERT overlay"
    if external_tei:
        detail += " with external TEI"
    if quality_rerank:
        detail += " with RERANK_ENABLED=true"
    return True, detail


def _dotnet_sdk_resolution_failed(output: str) -> bool:
    lower = output.lower()
    return (
        "a compatible .net sdk was not found" in lower
        or "sdk resolution" in lower
        or "install the [" in lower
        or "requested sdk version" in lower
    )


def _run_dotnet_test_in_sdk_container() -> subprocess.CompletedProcess:
    mount = str(REPO_ROOT).replace("\\", "/")
    return _run(
        [
            "docker",
            "run",
            "--rm",
            "-v",
            f"{mount}:/src",
            "-w",
            "/src",
            DOTNET_SDK_IMAGE,
            "dotnet",
            "test",
            "CodebaseIndexer.slnx",
            "--nologo",
        ]
    )


def run_dotnet_smoke() -> tuple[bool, str]:
    try:
        proc = _run(["dotnet", "test", "CodebaseIndexer.slnx", "--nologo"])
    except FileNotFoundError:
        proc = None
        detail = "dotnet executable not found on host"
    else:
        if proc.returncode == 0:
            return True, "dotnet test passed (host)"
        detail = proc.stderr or proc.stdout or "dotnet test failed"
        if not _dotnet_sdk_resolution_failed(detail):
            return False, detail[-4000:]

    container = _run_dotnet_test_in_sdk_container()
    if container.returncode != 0:
        cdetail = container.stderr or container.stdout or "dotnet test failed in SDK container"
        first = detail.splitlines()[0] if detail else "unknown"
        return False, (
            f"host SDK unavailable ({first}); "
            f"container fallback failed:\n{cdetail[-3500:]}"
        )
    return True, f"dotnet test passed (container {DOTNET_SDK_IMAGE})"


def http_ok(url: str, timeout: float = 3.0) -> tuple[bool, str]:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            body = resp.read(500).decode("utf-8", errors="replace")
            return True, body[:200]
    except urllib.error.HTTPError as exc:
        return False, f"HTTP {exc.code}"
    except Exception as exc:
        return False, str(exc)


def wait_http(url: str, *, attempts: int = 30, interval: float = 2.0) -> tuple[bool, str]:
    last = ""
    for _ in range(attempts):
        ok, msg = http_ok(url)
        if ok:
            return True, msg
        last = msg
        time.sleep(interval)
    return False, last


def preflight_host_tei(*, tei_url: str = HOST_TEI_URL) -> tuple[bool, str]:
    ok, detail = http_ok(f"{tei_url.rstrip('/')}/health")
    if not ok:
        return False, f"host TEI not healthy at {tei_url}: {detail}"
    return True, detail


def check_tei_container_absent(
    *,
    tei_container: str = TEI_CONTAINER,
    run_cmd: Callable[..., subprocess.CompletedProcess] | None = None,
) -> tuple[bool, str]:
    runner = run_cmd or _run
    proc = runner(
        ["docker", "ps", "--filter", f"name={tei_container}", "--format", "{{.Names}}"]
    )
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or "docker ps failed").strip()
        return False, detail[-2000:]
    names = (proc.stdout or "").strip()
    if names:
        return False, f"container present: {names}"
    return True, "no bundled tei container"


def tei_embed_smoke(
    *,
    tei_url: str = TEI_URL,
    model: str = JINA_DENSE_MODEL,
    vector_size: int = DENSE_VECTOR_SIZE,
) -> tuple[bool, str]:
    payload = json.dumps({"model": model, "input": "gpu integration probe"}).encode()
    req = urllib.request.Request(
        f"{tei_url.rstrip('/')}/v1/embeddings",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            body = json.loads(resp.read().decode("utf-8"))
            items = body.get("data") or []
            if not items:
                return False, "no embedding data"
            dim = len(items[0].get("embedding") or [])
            if dim != vector_size:
                return False, f"dimension {dim}, expected {vector_size}"
            return True, f"dim={dim}"
    except urllib.error.HTTPError as exc:
        err_body = exc.read(500).decode("utf-8", errors="replace")
        return False, f"HTTP {exc.code}: {err_body}"
    except Exception as exc:
        return False, str(exc)


def run_aspire_service_map_smoke() -> tuple[bool, str]:
    env = os.environ.copy()
    env["WORKSPACE_PATH"] = str(REPO_ROOT.parent.resolve())
    proc = _run(["python", "scripts/smoke_aspire_service_map.py"], cwd=REPO_ROOT, env=env)
    detail = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode == 0:
        return True, detail[-2000:] or "aspire service-map smoke passed"
    return False, detail[-4000:] or "aspire service-map smoke failed"


def run_validate_labels() -> tuple[bool, str]:
    try:
        proc = _run(
            [
                "uv",
                "run",
                "python",
                "-m",
                "benchmarks.eval_retrieval",
                "--validate-labels",
            ],
            cwd=BENCHMARKS,
            env=_host_test_env(),
        )
    except FileNotFoundError as exc:
        return False, f"uv not available: {exc}"
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode == 0, out.strip()[-2000:]


def run_quality_eval(
    *,
    compare: Path,
    threshold: float,
    rerank: bool,
    mcp_url: str,
) -> tuple[str, str]:
    cmd = [
        "uv",
        "run",
        "python",
        "-m",
        "benchmarks.eval_retrieval",
        "--mcp-url",
        mcp_url,
        "--compare",
        str(compare),
        "--threshold",
        str(threshold),
        "--output",
        str(BENCHMARKS / ".eval-integration-results.json"),
    ]
    if rerank:
        cmd.append("--rerank")
    proc = _run(cmd, cwd=BENCHMARKS, env=_host_test_env())
    out = (proc.stdout or "") + (proc.stderr or "")
    if "SKIP:" in out:
        return "skip", out.strip()[-2000:]
    if proc.returncode == 0:
        return "pass", out.strip()[-2000:]
    return "fail", out.strip()[-2000:]


def run_performance_report(*, compare: Path) -> tuple[str, str]:
    """Report-only — Python bench is a skip stub after Phase 7."""
    cmd = [
        "uv",
        "run",
        "python",
        "-m",
        "benchmarks.bench",
        "--compare",
        str(compare),
        "--output",
        str(BENCHMARKS / ".bench-integration-results.json"),
    ]
    proc = _run(cmd, cwd=BENCHMARKS, env=_host_test_env())
    out = (proc.stdout or "") + (proc.stderr or "")
    if "SKIP:" in out:
        return "skipped", out.strip()[-2000:]
    if proc.returncode == 0:
        return "pass", out.strip()[-2000:]
    return "warn", out.strip()[-2000:]


def run_index_golden_via_mcp(mcp_url: str = MCP_URL) -> tuple[bool, str]:
    script = REPO_ROOT / "scripts" / "reindex_graphrag.py"
    if not script.is_file():
        return False, f"missing {script}"
    env = _host_test_env()
    env["MCP_URL"] = mcp_url
    proc = _run([sys.executable, str(script)], cwd=REPO_ROOT, env=env)
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode == 0, out.strip()[-2000:]


def run_quality_validation(
    *,
    compare: Path,
    threshold: float,
    rerank: bool,
    mcp_url: str = MCP_URL,
) -> dict[str, dict[str, str]]:
    rows: dict[str, dict[str, str]] = {}

    ok, detail = run_validate_labels()
    rows["validate_labels"] = {
        "status": "pass" if ok else "fail",
        "detail": detail,
    }
    if not ok:
        indexed, index_detail = run_index_golden_via_mcp(mcp_url)
        rows["index_golden"] = {
            "status": "pass" if indexed else "fail",
            "detail": index_detail,
        }
        if indexed:
            ok, detail = run_validate_labels()
            rows["validate_labels_retry"] = {
                "status": "pass" if ok else "fail",
                "detail": detail,
            }

    if not ok:
        rows["eval_retrieval"] = {
            "status": "fail",
            "detail": "skipped — golden labels not present in Qdrant after index attempt",
        }
        return rows

    status, detail = run_quality_eval(
        compare=compare,
        threshold=threshold,
        rerank=rerank,
        mcp_url=mcp_url,
    )
    rows["eval_retrieval"] = {"status": status, "detail": detail}
    return rows


def quality_validation_passed(rows: dict[str, dict[str, str]]) -> bool:
    eval_row = rows.get("eval_retrieval", {})
    return eval_row.get("status") == "pass"


def _neo4j_auth_and_write_ok() -> tuple[bool, str]:
    proc = _run(
        [
            "docker",
            "exec",
            NEO4J_CONTAINER,
            "cypher-shell",
            "-u",
            "neo4j",
            "-p",
            GRAPH_INTEGRATION_PASSWORD,
            "CREATE (n:__GraphSmoke {k: 1}) DELETE n RETURN 1 AS ok",
        ]
    )
    detail = ((proc.stdout or "") + (proc.stderr or "")).strip()
    if proc.returncode != 0:
        return False, detail[-2000:] or "cypher-shell auth/write failed"
    if "ok" not in detail.lower() and "1" not in detail:
        return False, detail[-2000:] or "cypher-shell returned unexpected output"
    return True, "neo4j auth+write ok"


def run_graph_validation(*, external_tei: bool = False) -> tuple[str, str]:
    ok, detail = wait_http(NEO4J_URL)
    if not ok:
        return "fail", f"neo4j not healthy: {detail}"

    ok, auth_detail = _neo4j_auth_and_write_ok()
    if not ok:
        return "fail", f"neo4j auth/write failed: {auth_detail}"

    logs = _run(
        aspire_compose_cmd(
            "logs",
            "--no-color",
            "--tail",
            "500",
            "mcp",
            graph=True,
            gpu_colbert=get_accelerator() == "gpu",
            external_tei=external_tei,
        )
    )
    out = (logs.stdout or "") + (logs.stderr or "")
    if "graph_enabled" not in out:
        return "fail", "mcp did not log graph_enabled at startup"
    if "graph_disabled" in out:
        return "fail", "mcp logged graph_disabled (graph env not applied)"
    return (
        "pass",
        "neo4j healthy; auth+write ok; mcp registered expand_search_context (graph_enabled)",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Aspire Docker Compose integration harness")
    parser.add_argument("--keep", action="store_true", help="Leave stack running after tests")
    parser.add_argument("--skip-deploy", action="store_true", help="Assume stack already up")
    parser.add_argument("--json", action="store_true", help="Print machine-readable report on stdout")
    parser.add_argument(
        "--quality-validation",
        action="store_true",
        help="Run golden-set validate + eval_retrieval vs baseline (after deploy)",
    )
    parser.add_argument(
        "--quality-rerank",
        action="store_true",
        help="Pass --rerank to eval_retrieval (ColBERT must be indexed)",
    )
    parser.add_argument(
        "--quality-threshold",
        type=float,
        default=0.0,
        help="Fail quality eval when metrics drop more than N%% vs baseline (0 = report-only)",
    )
    parser.add_argument(
        "--quality-compare",
        type=Path,
        default=EVAL_BASELINE,
        help="Baseline JSON for eval_retrieval --compare",
    )
    parser.add_argument(
        "--performance-report",
        action="store_true",
        help="Run benchmarks.bench stub (report-only; does not fail harness)",
    )
    parser.add_argument(
        "--graph",
        action="store_true",
        help="Bring up Neo4j overlay (docker-compose.aspire.neo4j.yml) with Graph__*",
    )
    parser.add_argument(
        "--external-tei",
        action="store_true",
        help="Use host-native TEI at 127.0.0.1:8080 (ADR 0029); omit bundled tei service",
    )
    parser.add_argument(
        "--aspire-stack",
        action="store_true",
        help="No-op alias (Aspire is the production default since ADR 0030 Phase 7)",
    )
    parser.add_argument(
        "--bench-compare",
        type=Path,
        default=BENCH_BASELINE,
        help="Baseline JSON for benchmarks.bench --compare",
    )
    args = parser.parse_args()

    report: dict = {
        "aspire_stack": True,
        "external_tei": args.external_tei,
        "deploy": {"status": "pending", "detail": ""},
        "host_tei_preflight": {"status": "pending", "detail": ""},
        "qdrant_health": {"status": "pending", "detail": ""},
        "mcp_health": {"status": "pending", "detail": ""},
        "mcp_alive": {"status": "pending", "detail": ""},
        "mcp_readiness_tei_down": {"status": "pending", "detail": ""},
        "tei_health": {"status": "pending", "detail": ""},
        "colbert_health": {"status": "pending", "detail": ""},
        "tei_embed_smoke": {"status": "pending", "detail": ""},
        "tei_container_absent": {"status": "pending", "detail": ""},
        "dotnet_smoke": {"status": "pending", "detail": ""},
        "aspire_service_map_smoke": {"status": "pending", "detail": ""},
        "quality_validation": {
            "required": args.quality_validation,
            "status": "skipped",
            "checks": {},
        },
        "performance_report": {
            "requested": args.performance_report,
            "status": "skipped",
            "detail": "",
        },
        "graph_validation": {"required": args.graph, "status": "skipped", "detail": ""},
        "verdict": "pending",
    }

    if not docker_available():
        report["verdict"] = "skip"
        report["deploy"] = {"status": "skip", "detail": "docker not available"}
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print("SKIP: Docker not available")
        return 2

    if args.external_tei:
        os.environ["ACCELERATOR"] = "cpu"
    elif not os.environ.get("ACCELERATOR"):
        os.environ["ACCELERATOR"] = "cpu"

    try:
        require_gpu()
    except GpuRequiredError as exc:
        report["verdict"] = "fail"
        report["deploy"] = {"status": "fail", "detail": str(exc)}
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print(f"FAIL: {exc}")
        return 1

    write_integration_env(
        REPO_ROOT.parent,
        graph=args.graph,
        external_tei=args.external_tei,
        quality_rerank=args.quality_rerank,
    )

    if args.external_tei:
        ok, detail = preflight_host_tei()
        report["host_tei_preflight"] = {
            "status": "pass" if ok else "fail",
            "detail": detail,
        }
        if not ok:
            report["verdict"] = "fail"
            if args.json:
                print(json.dumps(report, indent=2))
            else:
                print(f"FAIL: host TEI preflight — {detail}")
            return 1
    else:
        report["host_tei_preflight"] = {
            "status": "skipped",
            "detail": "bundled tei path",
        }

    if args.skip_deploy:
        report["deploy"] = {"status": "skipped", "detail": "--skip-deploy"}
    else:
        ok, detail = deploy_aspire_stack(
            graph=args.graph,
            quality_rerank=args.quality_rerank,
            external_tei=args.external_tei,
        )
        report["deploy"] = {"status": "pass" if ok else "fail", "detail": detail}
        if not ok:
            report["verdict"] = "fail"
            if args.json:
                print(json.dumps(report, indent=2))
            else:
                print(f"FAIL: aspire deploy — {detail}")
            return 1

    ok, detail = wait_http(MCP_HEALTH_URL, attempts=30, interval=2.0)
    report["mcp_health"] = {"status": "pass" if ok else "fail", "detail": detail}
    ok, detail = http_ok(MCP_ALIVE_URL)
    report["mcp_alive"] = {"status": "pass" if ok else "fail", "detail": detail}
    ok, detail = http_ok(f"{QDRANT_URL}/healthz")
    report["qdrant_health"] = {"status": "pass" if ok else "fail", "detail": detail}

    if args.external_tei:
        ok, detail = check_tei_container_absent()
        report["tei_container_absent"] = {
            "status": "pass" if ok else "fail",
            "detail": detail,
        }
        ok, detail = http_ok(f"{HOST_TEI_URL}/health")
        report["tei_health"] = {"status": "pass" if ok else "fail", "detail": detail}
        ok, detail = tei_embed_smoke(tei_url=HOST_TEI_URL)
        report["tei_embed_smoke"] = {"status": "pass" if ok else "fail", "detail": detail}
    else:
        ok, detail = http_ok(f"{TEI_URL}/health")
        report["tei_health"] = {"status": "pass" if ok else "fail", "detail": detail}
        ok, detail = tei_embed_smoke()
        report["tei_embed_smoke"] = {"status": "pass" if ok else "fail", "detail": detail}
        report["tei_container_absent"] = {
            "status": "skipped",
            "detail": "bundled tei path",
        }

    ok, detail = wait_http(COLBERT_HEALTH_URL, attempts=30, interval=2.0)
    report["colbert_health"] = {"status": "pass" if ok else "fail", "detail": detail}
    if ok and get_accelerator() == "gpu":
        try:
            with urllib.request.urlopen(COLBERT_HEALTH_URL, timeout=10) as resp:
                body = resp.read().decode("utf-8", errors="replace")
            if '"device":"cuda"' not in body and '"device": "cuda"' not in body:
                report["colbert_health"] = {
                    "status": "fail",
                    "detail": f"ACCELERATOR=gpu but ColBERT health device != cuda: {body[:500]}",
                }
        except Exception as exc:  # noqa: BLE001
            report["colbert_health"] = {
                "status": "fail",
                "detail": f"ColBERT GPU health parse failed: {exc}",
            }

    ok, detail = run_dotnet_smoke()
    report["dotnet_smoke"] = {"status": "pass" if ok else "fail", "detail": detail}

    ok, detail = run_aspire_service_map_smoke()
    report["aspire_service_map_smoke"] = {
        "status": "pass" if ok else "fail",
        "detail": detail,
    }

    # ADR 0031: TEI-down readiness split — /health fails, /alive stays up.
    if args.external_tei:
        report["mcp_readiness_tei_down"] = {
            "status": "skipped",
            "detail": "external tei — bundled TEI stop not applicable",
        }
    else:
        stop = _run(["docker", "stop", TEI_CONTAINER])
        if stop.returncode != 0:
            report["mcp_readiness_tei_down"] = {
                "status": "fail",
                "detail": (stop.stderr or stop.stdout or "docker stop tei failed")[-2000:],
            }
        else:
            time.sleep(2.0)
            ready_ok, ready_detail = http_ok(MCP_HEALTH_URL)
            alive_ok, alive_detail = http_ok(MCP_ALIVE_URL)
            split_ok = (not ready_ok) and alive_ok
            report["mcp_readiness_tei_down"] = {
                "status": "pass" if split_ok else "fail",
                "detail": (
                    f"after TEI stop: /health ok={ready_ok} ({ready_detail}); "
                    f"/alive ok={alive_ok} ({alive_detail})"
                ),
            }
            start = _run(["docker", "start", TEI_CONTAINER])
            if start.returncode != 0:
                report["mcp_readiness_tei_down"] = {
                    "status": "fail",
                    "detail": (
                        report["mcp_readiness_tei_down"]["detail"]
                        + "; TEI restart failed: "
                        + (start.stderr or start.stdout or "")[-1000:]
                    ),
                }
            else:
                wait_http(f"{TEI_URL}/health", attempts=60, interval=5.0)
                wait_http(MCP_HEALTH_URL, attempts=30, interval=2.0)

    if args.graph:
        graph_status, graph_detail = run_graph_validation(external_tei=args.external_tei)
        report["graph_validation"] = {
            "required": True,
            "status": graph_status,
            "detail": graph_detail,
        }

    if args.quality_validation:
        quality_rows = run_quality_validation(
            compare=args.quality_compare,
            threshold=args.quality_threshold,
            rerank=args.quality_rerank,
            mcp_url=MCP_URL,
        )
        report["quality_validation"] = {
            "required": True,
            "status": "pass" if quality_validation_passed(quality_rows) else "fail",
            "threshold": args.quality_threshold,
            "rerank": args.quality_rerank,
            "compare": str(args.quality_compare),
            "mcp_url": MCP_URL,
            "checks": quality_rows,
        }

    if args.performance_report:
        perf_status, perf_detail = run_performance_report(compare=args.bench_compare)
        report["performance_report"] = {
            "requested": True,
            "status": perf_status,
            "detail": perf_detail,
            "compare": str(args.bench_compare),
        }

    required = (
        "deploy",
        "mcp_health",
        "mcp_alive",
        "mcp_readiness_tei_down",
        "qdrant_health",
        "tei_health",
        "colbert_health",
        "dotnet_smoke",
        "aspire_service_map_smoke",
    )
    required_ok = all(report[k]["status"] in ("pass", "skipped") for k in required)
    if args.external_tei:
        required_ok = required_ok and report["tei_container_absent"]["status"] == "pass"
    if args.quality_validation:
        required_ok = required_ok and report["quality_validation"]["status"] == "pass"
    if args.graph:
        required_ok = required_ok and report["graph_validation"]["status"] == "pass"
    report["verdict"] = "pass" if required_ok else "fail"

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"Verdict: {report['verdict']}")

    if not args.keep and not args.skip_deploy:
        down_args = ["down", "--remove-orphans"]
        if args.graph:
            down_args.append("-v")
        _run(
            aspire_compose_cmd(
                *down_args,
                graph=args.graph,
                gpu_colbert=get_accelerator() == "gpu",
                external_tei=args.external_tei,
            )
        )
    return 0 if report["verdict"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
