#!/usr/bin/env python3
"""Deploy the stack with Docker Compose and run integration checks.

Used by the ADR integration-tester agent and local pre-PR validation.

From repository root:

    python scripts/run_compose_integration.py
    python scripts/run_compose_integration.py --keep
    python scripts/run_compose_integration.py --skip-deploy   # stack already up
    python scripts/run_compose_integration.py --json --quality-validation
    python scripts/run_compose_integration.py --json --quality-validation --quality-rerank --quality-threshold 5
    python scripts/run_compose_integration.py --json --performance-report

Exits 0 when required checks pass, 1 on failure, 2 when Docker unavailable (skip).

Before first run with bundled Ollama, pull the embed model:

    docker exec codeindexer_ollama ollama pull unclemusclez/jina-embeddings-v2-base-code
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
from collections.abc import Callable
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.accelerator import GpuRequiredError, get_accelerator, require_gpu
from scripts.compose_files import compose_file_args

MCP_SERVER = REPO_ROOT / "mcp_server"
ENV_FILE = REPO_ROOT / ".env.compose.integration"
EVAL_BASELINE = MCP_SERVER / "benchmarks" / "fixtures" / "eval_baseline.json"
BENCH_BASELINE = MCP_SERVER / "benchmarks" / "baseline.json"
REINDEX_SCRIPT = REPO_ROOT / "scripts" / "reindex_graphrag.py"
COMPOSE_BASE = ["docker", "compose", "--env-file", str(ENV_FILE)]
COMPOSE_PROFILE = "bundled-ollama"
SERVICES = ("qdrant", "ollama", "mcp_server")
QDRANT_URL = "http://127.0.0.1:6333"
MCP_HEALTH_URL = "http://127.0.0.1:8000/health"
OLLAMA_URL = "http://127.0.0.1:11434"
OLLAMA_CONTAINER = "codeindexer_ollama"
JINA_OLLAMA_MODEL = "unclemusclez/jina-embeddings-v2-base-code"

# Host-side pytest/smoke must match compose Jina preset — not developer .env.
_INTEGRATION_EMBED_ENV = {
    "DENSE_EMBED_MODEL": "jinaai/jina-embeddings-v2-base-code",
    "OLLAMA_EMBED_MODEL": "unclemusclez/jina-embeddings-v2-base-code",
    "DENSE_EMBED_VECTOR_SIZE": "768",
    "OLLAMA_URL": OLLAMA_URL,
    "SPARSE_EMBED_MODEL": "Qdrant/bm25",
    "SPARSE_THREADS": "2",
}


def _host_test_env() -> dict[str, str]:
    env = os.environ.copy()
    env["QDRANT_URL"] = QDRANT_URL
    env.update(_INTEGRATION_EMBED_ENV)
    return env


def _run(cmd: list[str], *, cwd: Path | None = None, env: dict | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        cwd=cwd or REPO_ROOT,
        env=env,
        text=True,
        capture_output=True,
    )


def docker_available() -> bool:
    return _run(["docker", "info"]).returncode == 0


def write_integration_env(workspace_root: Path) -> None:
    """Minimal compose env for integration — does not touch developer .env."""
    workspace = workspace_root.resolve()
    accelerator = get_accelerator()
    ollama_gpu = "1" if accelerator == "gpu" else "0"
    content = f"""# Generated by scripts/run_compose_integration.py — safe to delete
# Pre-step (bundled Ollama): docker exec codeindexer_ollama ollama pull unclemusclez/jina-embeddings-v2-base-code
WORKSPACE_ROOT={workspace}
ACCELERATOR={accelerator}
MCP_MEM_LIMIT=4g
QDRANT_MEM_LIMIT=2g
MCP_CPUS=4
QDRANT_CPUS=2
OMP_NUM_THREADS=2
DENSE_EMBED_MODEL=jinaai/jina-embeddings-v2-base-code
SPARSE_EMBED_MODEL=Qdrant/bm25
DENSE_EMBED_VECTOR_SIZE=768
SPARSE_THREADS=2
COMPOSE_PROFILES={COMPOSE_PROFILE}
OLLAMA_URL=http://ollama:11434
OLLAMA_EMBED_MODEL=unclemusclez/jina-embeddings-v2-base-code
OLLAMA_GPU={ollama_gpu}
OLLAMA_TIMEOUT=600
OLLAMA_MEM_LIMIT=3g
OLLAMA_CPUS=2
FLUSH_EVERY=128
RERANK_ENABLED=false
"""
    ENV_FILE.write_text(content, encoding="utf-8")


def compose_cmd(*args: str) -> list[str]:
    env = dict(os.environ)
    if ENV_FILE.is_file():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            env[key] = value
    return [*COMPOSE_BASE, *compose_file_args(env=env), *args]


def deploy() -> tuple[bool, str]:
    build = _run(compose_cmd("build", "mcp_server"))
    if build.returncode != 0:
        return False, build.stderr or build.stdout or "compose build failed"
    up = _run(
        compose_cmd(
            "--profile",
            COMPOSE_PROFILE,
            "up",
            "-d",
            "--wait",
            *SERVICES,
        )
    )
    if up.returncode != 0:
        return False, up.stderr or up.stdout or "compose up failed"
    return True, "deployed"


def http_ok(url: str, timeout: float = 3.0) -> tuple[bool, str]:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            body = resp.read(500).decode("utf-8", errors="replace")
            return True, body[:200]
    except urllib.error.HTTPError as exc:
        return False, f"HTTP {exc.code}"
    except Exception as exc:
        return False, str(exc)


def wait_http(url: str, *, attempts: int = 30, interval: float = 2.0) -> tuple[bool, str]:
    last = ""
    for _ in range(attempts):
        ok, msg = http_ok(url)
        if ok:
            return True, msg
        last = msg
        time.sleep(interval)
    return False, last


def ollama_ps_shows_gpu(ps_output: str) -> bool:
    """True when ``ollama ps`` lists a loaded model with GPU in PROCESSOR."""
    data_lines = [
        line
        for line in ps_output.splitlines()
        if line.strip() and not line.upper().startswith("NAME")
    ]
    if not data_lines:
        return False
    return any("gpu" in line.lower() for line in data_lines)


def check_ollama_gpu_processor(
    *,
    embed_model: str = JINA_OLLAMA_MODEL,
    ollama_container: str = OLLAMA_CONTAINER,
    ollama_url: str = OLLAMA_URL,
    run_cmd: Callable[..., subprocess.CompletedProcess] | None = None,
    embed_fn: Callable[[str, str], tuple[bool, str]] | None = None,
) -> tuple[bool, str]:
    """Pull Jina, embed once, assert ``ollama ps`` reports GPU processor (ADR 0022 P3)."""
    runner = run_cmd or _run
    embed = embed_fn or _ollama_embed

    pull = runner(
        ["docker", "exec", ollama_container, "ollama", "pull", embed_model],
    )
    if pull.returncode != 0:
        detail = (pull.stderr or pull.stdout or "ollama pull failed").strip()
        return False, detail[-2000:]

    ok, detail = embed(ollama_url, embed_model)
    if not ok:
        return False, f"embed failed: {detail}"

    ps = runner(["docker", "exec", ollama_container, "ollama", "ps"])
    if ps.returncode != 0:
        detail = (ps.stderr or ps.stdout or "ollama ps failed").strip()
        return False, detail[-2000:]

    ps_out = (ps.stdout or "") + (ps.stderr or "")
    if ollama_ps_shows_gpu(ps_out):
        return True, ps_out.strip()[-2000:]
    return False, f"PROCESSOR not GPU:\n{ps_out.strip()[-2000:]}"


def _ollama_embed(ollama_url: str, model: str) -> tuple[bool, str]:
    payload = json.dumps({"model": model, "input": "gpu integration probe"}).encode()
    req = urllib.request.Request(
        f"{ollama_url}/api/embed",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            body = resp.read(500).decode("utf-8", errors="replace")
            return True, body[:200]
    except urllib.error.HTTPError as exc:
        err_body = exc.read(500).decode("utf-8", errors="replace")
        return False, f"HTTP {exc.code}: {err_body}"
    except Exception as exc:
        return False, str(exc)


def run_pytest_integration() -> tuple[bool, str]:
    proc = _run(
        ["uv", "run", "pytest", "tests/test_storage_integration.py", "-q", "--tb=short"],
        cwd=MCP_SERVER,
        env=_host_test_env(),
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode == 0, out.strip()[-2000:]


def run_smoke_optional() -> tuple[str, str]:
    """recommend_code smoke — optional when Ollama + indexed collection available."""
    proc = _run(
        ["uv", "run", "python", "scripts/smoke_recommend_code.py"],
        cwd=MCP_SERVER,
        env=_host_test_env(),
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode == 0 and "SKIP:" in out:
        return "skipped", out.strip()[-500:]
    if proc.returncode == 0:
        return "pass", out.strip()[-500:]
    return "fail", out.strip()[-1000:]


def run_validate_labels() -> tuple[bool, str]:
    proc = _run(
        [
            "uv",
            "run",
            "python",
            "-m",
            "benchmarks.eval_retrieval",
            "--validate-labels",
        ],
        cwd=MCP_SERVER,
        env=_host_test_env(),
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode == 0, out.strip()[-2000:]


def run_index_golden_collection() -> tuple[bool, str]:
    if not REINDEX_SCRIPT.is_file():
        return False, f"missing {REINDEX_SCRIPT}"
    proc = _run(
        [sys.executable, str(REINDEX_SCRIPT)],
        cwd=REPO_ROOT,
        env=_host_test_env(),
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode == 0, out.strip()[-2000:]


def run_quality_eval(
    *,
    compare: Path,
    threshold: float,
    rerank: bool,
) -> tuple[str, str]:
    """Return (status, detail) — pass / fail / skip."""
    cmd = [
        "uv",
        "run",
        "python",
        "-m",
        "benchmarks.eval_retrieval",
        "--compare",
        str(compare),
        "--threshold",
        str(threshold),
        "--output",
        str(MCP_SERVER / ".eval-integration-results.json"),
    ]
    if rerank:
        cmd.append("--rerank")
    proc = _run(cmd, cwd=MCP_SERVER, env=_host_test_env())
    out = (proc.stdout or "") + (proc.stderr or "")
    if "SKIP:" in out:
        return "skip", out.strip()[-2000:]
    if proc.returncode == 0:
        return "pass", out.strip()[-2000:]
    return "fail", out.strip()[-2000:]


def run_performance_report(*, compare: Path) -> tuple[str, str]:
    """Report-only bench.py — never fails the harness verdict."""
    cmd = [
        "uv",
        "run",
        "python",
        "-m",
        "benchmarks.bench",
        "--files",
        "50",
        "--iterations",
        "10",
        "--compare",
        str(compare),
        "--threshold",
        "0",
        "--output",
        str(MCP_SERVER / ".bench-integration-results.json"),
    ]
    proc = _run(cmd, cwd=MCP_SERVER, env=_host_test_env())
    out = (proc.stdout or "") + (proc.stderr or "")
    if "SKIP:" in out:
        return "skipped", out.strip()[-2000:]
    if proc.returncode == 0:
        return "pass", out.strip()[-2000:]
    return "warn", out.strip()[-2000:]


def run_quality_validation(
    *,
    compare: Path,
    threshold: float,
    rerank: bool,
) -> dict[str, dict[str, str]]:
    """Validate labels, index golden collection if needed, run eval_retrieval."""
    rows: dict[str, dict[str, str]] = {}

    ok, detail = run_validate_labels()
    rows["validate_labels"] = {
        "status": "pass" if ok else "fail",
        "detail": detail,
    }
    if not ok:
        indexed, index_detail = run_index_golden_collection()
        rows["index_golden"] = {
            "status": "pass" if indexed else "fail",
            "detail": index_detail,
        }
        if indexed:
            ok, detail = run_validate_labels()
            rows["validate_labels_retry"] = {
                "status": "pass" if ok else "fail",
                "detail": detail,
            }

    if not ok:
        rows["eval_retrieval"] = {
            "status": "fail",
            "detail": "skipped — golden labels not present in Qdrant after index attempt",
        }
        return rows

    status, detail = run_quality_eval(
        compare=compare,
        threshold=threshold,
        rerank=rerank,
    )
    rows["eval_retrieval"] = {"status": status, "detail": detail}
    return rows


def quality_validation_passed(rows: dict[str, dict[str, str]]) -> bool:
    eval_row = rows.get("eval_retrieval", {})
    return eval_row.get("status") == "pass"


def teardown() -> None:
    _run(compose_cmd("--profile", COMPOSE_PROFILE, "down", "--remove-orphans"))


def main() -> int:
    parser = argparse.ArgumentParser(description="Docker Compose integration harness")
    parser.add_argument("--keep", action="store_true", help="Leave stack running after tests")
    parser.add_argument("--skip-deploy", action="store_true", help="Assume stack already up")
    parser.add_argument("--json", action="store_true", help="Print machine-readable report on stdout")
    parser.add_argument(
        "--quality-validation",
        action="store_true",
        help="Run golden-set validate + eval_retrieval vs baseline (after deploy)",
    )
    parser.add_argument(
        "--quality-rerank",
        action="store_true",
        help="Pass --rerank to eval_retrieval (ColBERT must be indexed)",
    )
    parser.add_argument(
        "--quality-threshold",
        type=float,
        default=0.0,
        help="Fail quality eval when metrics drop more than N%% vs baseline (0 = report-only)",
    )
    parser.add_argument(
        "--quality-compare",
        type=Path,
        default=EVAL_BASELINE,
        help="Baseline JSON for eval_retrieval --compare",
    )
    parser.add_argument(
        "--performance-report",
        action="store_true",
        help="Run bench.py vs baseline (report-only; does not fail harness)",
    )
    parser.add_argument(
        "--bench-compare",
        type=Path,
        default=BENCH_BASELINE,
        help="Baseline JSON for benchmarks.bench --compare",
    )
    args = parser.parse_args()

    report: dict = {
        "deploy": {"status": "pending", "detail": ""},
        "qdrant_health": {"status": "pending", "detail": ""},
        "mcp_health": {"status": "pending", "detail": ""},
        "ollama_health": {"status": "pending", "detail": ""},
        "ollama_gpu_processor": {"status": "pending", "detail": ""},
        "pytest_integration": {"status": "pending", "detail": ""},
        "smoke_recommend": {"status": "pending", "detail": ""},
        "quality_validation": {"required": args.quality_validation, "status": "skipped", "checks": {}},
        "performance_report": {"requested": args.performance_report, "status": "skipped", "detail": ""},
        "verdict": "pending",
    }

    if not docker_available():
        report["verdict"] = "skip"
        report["deploy"] = {"status": "skip", "detail": "docker not available"}
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print("SKIP: Docker not available")
        return 2

    write_integration_env(REPO_ROOT.parent)

    try:
        require_gpu()
    except GpuRequiredError as exc:
        report["verdict"] = "fail"
        report["deploy"] = {"status": "fail", "detail": str(exc)}
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print(f"FAIL: {exc}")
        return 1

    try:
        if args.skip_deploy:
            report["deploy"] = {"status": "skipped", "detail": "--skip-deploy"}
        else:
            ok, detail = deploy()
            report["deploy"] = {"status": "pass" if ok else "fail", "detail": detail}
            if not ok:
                report["verdict"] = "fail"
                if args.json:
                    print(json.dumps(report, indent=2))
                return 1

        ok, detail = wait_http(f"{QDRANT_URL}/healthz")
        report["qdrant_health"] = {"status": "pass" if ok else "fail", "detail": detail}

        ok, detail = wait_http(MCP_HEALTH_URL)
        report["mcp_health"] = {"status": "pass" if ok else "fail", "detail": detail}

        ok, detail = http_ok(f"{OLLAMA_URL}/api/tags")
        report["ollama_health"] = {
            "status": "pass" if ok else "warn",
            "detail": detail if ok else detail,
        }

        accelerator = get_accelerator()
        if accelerator == "gpu":
            ok, detail = check_ollama_gpu_processor()
            report["ollama_gpu_processor"] = {
                "status": "pass" if ok else "fail",
                "detail": detail,
            }
        else:
            report["ollama_gpu_processor"] = {
                "status": "skipped",
                "detail": f"ACCELERATOR={accelerator}",
            }

        ok, detail = run_pytest_integration()
        report["pytest_integration"] = {"status": "pass" if ok else "fail", "detail": detail}

        smoke_status, smoke_detail = run_smoke_optional()
        report["smoke_recommend"] = {"status": smoke_status, "detail": smoke_detail}

        if args.quality_validation:
            quality_rows = run_quality_validation(
                compare=args.quality_compare,
                threshold=args.quality_threshold,
                rerank=args.quality_rerank,
            )
            report["quality_validation"] = {
                "required": True,
                "status": "pass" if quality_validation_passed(quality_rows) else "fail",
                "threshold": args.quality_threshold,
                "rerank": args.quality_rerank,
                "compare": str(args.quality_compare),
                "checks": quality_rows,
            }

        if args.performance_report:
            perf_status, perf_detail = run_performance_report(compare=args.bench_compare)
            report["performance_report"] = {
                "requested": True,
                "status": perf_status,
                "detail": perf_detail,
                "compare": str(args.bench_compare),
            }

        required_ok = all(
            report[k]["status"] in ("pass", "skipped")
            for k in ("deploy", "qdrant_health", "mcp_health", "pytest_integration")
        )
        if get_accelerator() == "gpu":
            required_ok = required_ok and report["ollama_gpu_processor"]["status"] == "pass"
        if args.quality_validation:
            required_ok = required_ok and report["quality_validation"]["status"] == "pass"
        report["verdict"] = "pass" if required_ok else "fail"

        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print(f"Verdict: {report['verdict']}")
            for name, row in report.items():
                if name == "verdict":
                    continue
                print(f"  {name}: {row['status']}")

        return 0 if required_ok else 1
    finally:
        if not args.keep and not args.skip_deploy:
            teardown()


if __name__ == "__main__":
    raise SystemExit(main())
