#!/usr/bin/env python3
"""Resource-aware stack tuner CLI (ADR 0024).

Phase 1 delivers ``analyze`` and ``allocate``. ``tune`` and ``report`` are stubs
that point at later phases. The tuner is opt-in, offline, and non-destructive:
it prints to stdout or writes an explicit ``.env.tuned`` fragment, but never the
operator's ``.env``.

Examples::

    python scripts/tune_stack.py analyze --cpu --no-colbert --no-neo4j
    python scripts/tune_stack.py allocate --gpu --colbert --max-ram-gib 8
    python scripts/tune_stack.py allocate --gpu --neo4j --write .env.tuned
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.tune_alloc import (  # noqa: E402
    Budget,
    FeatureFlags,
    ServiceSet,
    build_allocation,
    default_reserve_gib,
    detect_host,
    render_env_fragment,
    resolve_budget,
    resolve_services,
    seed_knobs,
)

_VM_CAVEAT = (
    "Note: on Windows/macOS, Docker cgroup limits apply inside the Linux VM "
    "(Docker Desktop/WSL2). RAM detected here is host-visible; ensure the VM "
    "memory slider exposes at least --max-ram-gib to the stack."
)


def _tristate(pos: bool, neg: bool) -> bool | None:
    if pos:
        return True
    if neg:
        return False
    return None


def _flags_from_args(args: argparse.Namespace) -> FeatureFlags:
    return FeatureFlags(
        gpu=_tristate(args.gpu, args.cpu),
        colbert=_tristate(args.colbert, args.no_colbert),
        neo4j=_tristate(args.neo4j, args.no_neo4j),
    )


def _resolve(args: argparse.Namespace) -> tuple[Budget, ServiceSet]:
    host = detect_host()
    budget = resolve_budget(
        host,
        max_cpus=args.max_cpus,
        max_ram_gib=args.max_ram_gib,
        reserve_gib=args.reserve_gib,
    )
    services = resolve_services(_flags_from_args(args))
    return budget, services


def _print_table(rows: list[tuple[str, str]], *, indent: str = "  ") -> None:
    width = max((len(k) for k, _ in rows), default=0)
    for key, val in rows:
        print(f"{indent}{key.ljust(width)}  {val}")


def cmd_analyze(args: argparse.Namespace) -> int:
    host = detect_host()
    try:
        budget = resolve_budget(
            host,
            max_cpus=args.max_cpus,
            max_ram_gib=args.max_ram_gib,
            reserve_gib=args.reserve_gib,
        )
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    services = resolve_services(_flags_from_args(args))

    detected_ram = (
        f"{host.total_ram_gib:.1f}g" if host.total_ram_gib is not None else "undetected"
    )
    print("Host:")
    _print_table(
        [
            ("cpu_count", str(host.cpu_count)),
            ("total_ram", detected_ram),
        ]
    )
    print("Budget:")
    _print_table(
        [
            ("max_cpus", str(budget.max_cpus)),
            ("max_ram_gib", f"{budget.max_ram_gib:g}"),
            ("reserve_gib", f"{budget.reserve_gib:g}"),
            ("usable_cpus", str(budget.usable_cpus)),
            ("usable_ram_gib", f"{budget.usable_ram_gib:g}"),
        ]
    )
    print("Resolved topology:")
    _print_table(
        [
            ("accelerator", services.accelerator),
            ("tei", "external" if services.tei_external else str(services.tei)),
            ("colbert", str(services.colbert)),
            ("neo4j", str(services.neo4j)),
            ("active", ", ".join(services.active)),
        ]
    )
    print()
    print(_VM_CAVEAT)
    return 0


def cmd_allocate(args: argparse.Namespace) -> int:
    if args.write and Path(args.write).name == ".env":
        print(
            "error: refusing to write operator .env; choose e.g. --write .env.tuned",
            file=sys.stderr,
        )
        return 2

    try:
        budget, services = _resolve(args)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    allocation = build_allocation(budget, services)
    knobs = seed_knobs(allocation.ram_gib, allocation.cpus, services)
    fragment = render_env_fragment(allocation, services, knobs)

    header = (
        "# Generated by scripts/tune_stack.py allocate (ADR 0024 Phase 1)\n"
        f"# usable_ram_gib={budget.usable_ram_gib:g} usable_cpus={budget.usable_cpus} "
        f"accelerator={services.accelerator}\n"
        "# Starting point only - re-index after committing storage-knob changes."
    )
    body = fragment.render()

    if args.write:
        Path(args.write).write_text(header + "\n" + body + "\n", encoding="utf-8")
        print(f"wrote {args.write}")
    else:
        print(header)
        print(body)
    return 0


def _cmd_phase_stub(name: str, phase: str) -> int:
    print(
        f"'{name}' is not available yet: delivered in ADR 0024 {phase}. "
        f"Phase 1 provides 'analyze' and 'allocate' only.",
        file=sys.stderr,
    )
    return 2


def cmd_tune(args: argparse.Namespace) -> int:
    return _cmd_phase_stub("tune", "Phase 2/3 (seed bench + iterative search)")


def cmd_report(args: argparse.Namespace) -> int:
    return _cmd_phase_stub("report", "Phase 3 (tune-report.json rendering)")


def _add_global_flags(parser: argparse.ArgumentParser) -> None:
    accel = parser.add_mutually_exclusive_group()
    accel.add_argument("--gpu", action="store_true", help="Target GPU accelerator")
    accel.add_argument("--cpu", action="store_true", help="Target CPU-only accelerator")

    colbert = parser.add_mutually_exclusive_group()
    colbert.add_argument("--colbert", action="store_true", help="Enable ColBERT sidecar")
    colbert.add_argument(
        "--no-colbert", action="store_true", help="Disable ColBERT sidecar"
    )

    neo4j = parser.add_mutually_exclusive_group()
    neo4j.add_argument("--neo4j", action="store_true", help="Enable Neo4j GraphRAG sidecar")
    neo4j.add_argument("--no-neo4j", action="store_true", help="Disable Neo4j sidecar")

    parser.add_argument("--max-ram-gib", type=float, help="RAM budget (default floor(host/2))")
    parser.add_argument("--max-cpus", type=int, help="CPU budget (default host CPU count)")
    parser.add_argument(
        "--reserve-gib",
        type=float,
        default=default_reserve_gib(),
        help="Kernel/Docker/WSL2 headroom (default 4.0 on macOS, 2.5 elsewhere)",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="tune_stack.py",
        description="Resource-aware stack tuner (ADR 0024).",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_analyze = sub.add_parser("analyze", help="Print host, budget, resolved topology")
    _add_global_flags(p_analyze)
    p_analyze.set_defaults(func=cmd_analyze)

    p_allocate = sub.add_parser("allocate", help="Compute caps + knob seed env fragment")
    _add_global_flags(p_allocate)
    p_allocate.add_argument(
        "--write", metavar="PATH", help="Write fragment to PATH (never .env)"
    )
    p_allocate.set_defaults(func=cmd_allocate)

    p_tune = sub.add_parser("tune", help="(Phase 2/3) bench-driven knob search")
    _add_global_flags(p_tune)
    p_tune.set_defaults(func=cmd_tune)

    p_report = sub.add_parser("report", help="(Phase 3) render tune-report.json")
    _add_global_flags(p_report)
    p_report.add_argument("path", nargs="?", help="tune-report.json path")
    p_report.set_defaults(func=cmd_report)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
